name: Cache Delete Action
description: Delete GitHub Actions caches for a given key.

branding:
  icon: trash
  color: gray-dark

inputs:
  key:
    description: A key for identifying the cache.
    required: true
  ref:
    description: |
      The full Git reference for narrowing down the cache.
      The `ref` for a branch should be formatted as `refs/heads/<branch name>`.s
      To reference a pull request use `refs/pull/<number>/merge`.
    required: false
  token:
    description: The token to use to delete the cache.
    required: false
    default: ${{ github.token }}
  fail-on-not-found:
    description: |
      Whether to fail the action if the cache is not found.
    required: false
    default: 'false'

runs:
  using: node20
  main: dist/index.js
