name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: bun run test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: bun run lint

  run-action:
    needs:
      - test
      - lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - key: CACHE_KEY
            fail-on-not-found: false
            create-cache: true

          - key: CACHE_NOT_FOUND
            fail-on-not-found: false
            create-cache: false

          - key: CACHE_NOT_FOUND
            fail-on-not-found: true
            create-cache: false
    steps:
      - uses: actions/checkout@v4

      - name: Setup cache
        if: ${{ matrix.create-cache }}
        run: touch cache.txt
      - uses: actions/cache@v4
        if: ${{ matrix.create-cache }}
        with:
          key: ${{ matrix.key }}
          path: cache.txt

      - uses: ./
        id: cache-delete
        continue-on-error: ${{ matrix.fail-on-not-found }}
        with:
          key: ${{ matrix.key }}
          fail-on-not-found: ${{ matrix.fail-on-not-found }}

      - name: Check failure for not-found-error scenario
        if: ${{ matrix.fail-on-not-found && !matrix.create-cache && steps.cache-delete.outcome != 'failure' }}
        run: exit 1
